NETWORK_SCAN_SEMAPHORE_LIMIT = 20
NETWORK_SCAN_LOG_INTERVAL = 20
DEVICE_BIND_MAX_RETRIES = 2
ULTRA_FAST_POLLING_DURATION_SECONDS = 10
ULTRA_FAST_POLLING_INTERVAL = 0.5
ERROR_BACKOFF_BASE_DELAY = 0.5
ERROR_BACKOFF_MAX_ATTEMPTS = 4
CLEANUP_POLLING_INTERVAL_SECONDS = 1
STATS_LOG_INTERVAL_SECONDS = 60
RETRY_MANAGER_SLEEP_DURATION = 300
MAX_PROCESSING_TIMES_STORED = 1000
CONSECUTIVE_ERROR_RESET_VALUE = 0
DEFAULT_RETRY_ATTEMPTS = 3
DEFAULT_RETRY_DELAY = 1.0
DEFAULT_RETRY_BACKOFF = 2.0

